# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 525f369653e025423833cb5321583f0e3373f87aa73ea75cd34a5ed7d6d47bf9cd7a273ba3d4c415cf772cfc76a5a5bdd8f8a4a58e5d01e95522df8b4d7dccbe

test:
  secret_key_base: a6083d940b0e8fd089eb622020bae4baa6e87bbe679a725c9927b2a19d0d32d5a77e65b7dbcef319d2e46db69118622bc3f7a1ac10a8555d79ab37e02e455d6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
